spring:
  datasource:   # 1、配置数据源
    username: root
    password: 123456
#    url: jdbc:mysql://localhost:3306/springboot_ssm_test?characterEncoding=utf8&useSSL=false&useUnicode=true&allowMultiQueries=true&serverTimezone=GMT
    url: jdbc:mysql://192.168.13.49:3306/springboot_ssm_test?characterEncoding=utf8&useSSL=false&useUnicode=true&allowMultiQueries=true&serverTimezone=GMT
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:dao/**/*Dao.xml   # 2、配置Mybatis映射文件路径


