mcx:
  excludedUrl:
    - /api/test/login
    - /api/test/register
    - /api/test/send
    - /api/freemark/index
    - /api/test/sysnredis
    - /api/test/removeKey
    - /api/test/redisKey
    - /api/test/selectView
    - /api/test/fileRead
  urlPatterns: /api/*
