spring:
  profiles:
    active: dev
server:
  servlet:
    context-path: /bendi      #添加前缀
  port: 8585
  tomcat:
    uri-encoding: UTF-8
#  datasource:   # 1、配置数据源
#    username: root
#    password:
#    url: jdbc:mysql://121.37.3.100:3306/mysecret?characterEncoding=utf8&useSSL=false&useUnicode=true&allowMultiQueries=true&serverTimezone=GMT
#    driver-class-name: com.mysql.jdbc.Driver
#
#mybatis:
#  mapper-locations: classpath:dao/**/*Dao.xml   # 2、配置Mybatis映射文件路径
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #日志
jwt:
  # 单位秒  此处为 3天
  expiration: 259200


